# Generated by Django 3.1.6 on 2021-03-01 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20210301_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='tag',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Тег'),
        ),
    ]
