# Generated by Django 3.1.6 on 2021-03-01 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_articles_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='tag',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Тег'),
        ),
    ]
